name: chatgpt_api
description: ChatGPT API for Dart
version: 0.0.1
homepage: https://alfianlosari.com

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.23.1