name: chatgpt_client
description: Access OpenAI ChatGPT Public API using Dart Language. Supports native Dart project and all Flutter target platforms (iOS, Android, Windows, Linux, Web) It provides streamed and normal response when asking ChatGPT, the client also stores the converstation list history so it can be used on new prompt to make it aware of previous conversation context.
version: 1.0.0
homepage: https://github.com/alfianlosari/chatgpt_api_dart

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  test: ^1.23.1